1. Style issues in "failSame" and "failNotSame" methods: lines String formatted= ""; if (message != null)   formatted= message+" ";
can be replaced with just this:
String formatted= (message != null) ? message+" " : "";
(There's also some inconsistency in adding space to empty messages in "failSame" and "failNotSame" but not in "format".)

2. A small performance issue in "assertNull": 
the line
String message = "Expected: <null> but was: " + String.valueOf(object);
can be replaced with just this:
String message = object != null ? "Expected: <null> but was: " + object.toString() : "";
(We have found several tests that run slow because these strings are appended unnecessarily for null values.)